<?php

require_once 'webwala_config.php';

$constants = [
	'ASSETS_PATH' => '',
	'IMAGE_PATH' => '',	
	'DEFAULT_PAGE_INDEX' => 1,
	'PER_PAGE' => 20,
	'TABLE_LISTING_PER_PAGE' => 30,
	'ADMIN_FOLDER' => 'admin/',
	'FRONTENT_FOLDER' => 'frontent/',
	'AJAX_VIEW_FOLDER' => 'admin/ajax-view/',
	'DESIGN_FOLDER_PATH' => 'design/',
	'UPLOAD_FOLDER' => 'uploads/',
	'GUEST_FOLDER_PATH' => 'guest/',
	'STATIC_IMAGE_PATH' =>  $webwalaConfig['SITE_URL'] . 'images/upload-image.png',
	'FILE_STORAGE_PATH' => storage_path('app/'),
	'FILE_STORAGE_PATH_URL' => $webwalaConfig['SITE_URL'] . 'storage/app/',
	
	'ACTIVE_STATUS' => 1,
	'INACTIVE_STATUS' => 0,
	'ACTIVE_STATUS_TEXT' => 'Active',
	'INACTIVE_STATUS_TEXT' => 'Inactive',
	'ENABLE_STATUS' => 'Enable',
	'DISABLE_STATUS' => 'Disable',
	'SUCCESS_AJAX_CALL' => 1,
	'ERROR_AJAX_CALL' => 101,
	'SELECTION_YES' => 'Yes',
	'SELECTION_NO' => 'No',
	'ADD_REQUEST' => 'Add',
	'LEFT' => 'left',
	'RIGHT' => 'right',
	'EXCEL_EXPORT_BUTTON_TYPE' => 'excel',
	'ADMIN_THEME_COLOR' => '#fff',
	'ROLE_ADMIN' => 'admin',
	'ROLE_USER' => 'user',
	'LOGIN_SLUG' => 'login',
	'LOGIN_URL'	 => $webwalaConfig['SITE_URL'] . 'api/admin/v1/login',
	'LOGIN_TABLE' => 'login_master',
	'FORGOT_PASSWORD_URL'	 => $webwalaConfig['SITE_URL'] . 'forgot-password',
	'SUCCESS_LOGIN_REDIRECT' => $webwalaConfig['BACKEND_SITE_URL'] . 'dashboard',
	'DASHBOARD_URL' => $webwalaConfig['BACKEND_SITE_URL'] . 'dashboard',
	'CHANGE_PASSWORD_URL' => $webwalaConfig['BACKEND_SITE_URL'] . 'change-password',
	'LOGIN_HISTORY_URL' => $webwalaConfig['BACKEND_SITE_URL'] . 'login-history',
	'LOGIN_HISTORY_TABLE' => 'login_history',
	'SETTINGS_URL' => $webwalaConfig['BACKEND_SITE_URL'] . 'settings',
	'SETTINGS_TABLE' => 'settings',
	'COUNTER_MASTER_TABLE' => 'counter_master',
	'PAGE_NOT_FOUND_URL' => $webwalaConfig['BACKEND_SITE_URL'] . 'page-not-found',
	'USERS_URL' => $webwalaConfig['BACKEND_SITE_URL'] . 'users',
	'LOOKUP_MASTER_URL' => $webwalaConfig['BACKEND_SITE_URL'] . 'lookup',
	'LOOKUP_MASTER_TABLE' => 'lookup_master',
	'LOOKUP_MASTER_MODULE' => 'lookup',
	
	'ERROR_EXCEPTION_INFO_TABLE' => 'error_exception_info',
	'ERROR_EXCEPTION_URL' => $webwalaConfig['BACKEND_SITE_URL'] . 'exception',
	'MANAGE_SESSION_MESSAGES_URL' => $webwalaConfig['BACKEND_SITE_URL'] . 'manage-session-messages',
	'REMOVE_RECORD_URL' => $webwalaConfig['BACKEND_SITE_URL'] . 'removeRecord',

	'SUCCESS_API_STATUS_CODE' => 1,
	'ERROR_API_STATUS_CODE' => 101,
		
	'USER_MASTER' => 'users',
	'LOGIN_VERIFY_OTP_TABLE' => 'login_verify_otp',
	'CATEGORY_TABLE' => 'category',
	'category' => 'category',
	'CATEGORY_MASTER_URL' => $webwalaConfig['BACKEND_SITE_URL'] . 'category',
	'CATEGORY_MASTER_MODULE' => 'category',
	'SUB_CATEGORY_MASTER_MODULE' => 'sub-category',
	'SUB_CATEGORY_TABLE' => 'sub_category',
	'SUB_CATEGORY_MASTER_URL' => $webwalaConfig['BACKEND_SITE_URL'] . 'sub-category',
	//<---Need to remove this constants, while setup new project--->
	'LOCATION_MASTER_URL' =>$webwalaConfig['BACKEND_SITE_URL'] . 'locations',
	'LOCATION_MASTER' => 'location',
	'LOCATION_LOOKUP' => 'locations',
	'TYPE_MASTER_URL' => $webwalaConfig['BACKEND_SITE_URL'] . 'types',
	'TYPE_LOOKUP' => 'types',
	'TYPE_MASTER' => 'type',
	//<---Need to remove this constants, while setup new project--->

	'CONTACT_MASTER' => 'contect_master',
	'NEWSLATTER_TABLE' => 'newslatter_master',
	'SERVICE_TABLE' => 'service_master',
	'TESTINOMIAL_TABLE' => 'testinomial_master',
	'CLIENT_TABLE' => 'client_master',
	'BLOG_TABLE' => 'blog_master',
	'SEOCONTENT_TABLE' => 'seo_content_master',	
	'CATEGORY_TABLE' => 'category_master',	
	'COUNTER_MASTER_TABLE' => 'counter_master',

	'HOME_URL' => $webwalaConfig['SITE_URL'] . '',
	'ABOUT_URL' => $webwalaConfig['SITE_URL'] . 'about',
	'CAREER_URL' => $webwalaConfig['SITE_URL'] . 'career',
	'DEVELOPMENT_URL' => $webwalaConfig['SITE_URL'] . 'developmentprocess',
	'WEBDEVELOPMENT_URL' => $webwalaConfig['SITE_URL'] . 'webdevlopment',
	'APPDEVELOPMENT_URL' => $webwalaConfig['SITE_URL'] . 'appdevlopment',
	'DIGITALMARKETING_URL' => $webwalaConfig['SITE_URL'] . 'digitalmarketing',
	'GRAPHICSLOGO_URL' => $webwalaConfig['SITE_URL'] . 'graphicslogo',
	'QATESTING_URL' => $webwalaConfig['SITE_URL'] . 'qatesting',
	'DIGITALCARD_URL' => $webwalaConfig['SITE_URL'] . 'digitalcard',
	'HOSTINGSERVICE_URL' => $webwalaConfig['SITE_URL'] . 'hostingservice',
	'SUPPORT_URL' => $webwalaConfig['SITE_URL'] . 'support',
	'PHPINTERNSHIP_URL' => $webwalaConfig['SITE_URL'] . 'phpinternship',
	'WEBINTERNSHIP_URL' => $webwalaConfig['SITE_URL'] . 'webinternship',
	'FLUTTERINTERNSHIP_URL' => $webwalaConfig['SITE_URL'] . 'flutterinternship',
	'REACTINTERNSHIP_URL' => $webwalaConfig['SITE_URL'] . 'reactinternship',
	'NODEINTERNSHIP_URL' => $webwalaConfig['SITE_URL'] . 'nodeinternship',
	'PORTFOLIO_URL' => $webwalaConfig['SITE_URL'] . 'portfolio',
	'BLOG_URL' => $webwalaConfig['SITE_URL'] . 'blog',
	'CONTACT_URL' => $webwalaConfig['SITE_URL'] . 'contact-us',
	'SERVICE_URL' => $webwalaConfig['SITE_URL'] . 'service',
	'INTERNSHIP_URL' => $webwalaConfig['SITE_URL'] . 'internship',
	'PRIVICYPOLICY_URL' => $webwalaConfig['SITE_URL'] . 'privicypolicy',
	'TERMSCONDITION_URL' => $webwalaConfig['SITE_URL'] . 'termcondition',
	'NEWSLATTER_URL' => $webwalaConfig['SITE_URL'] . 'newslatter',
	
];
return array_merge($constants , $webwalaConfig );